### ISSUE TITLE
Добавить stack navigator

### ISSUE THREAD

**Issue by Arkaides** [team-dev-spring-2022/teamBanana#20]
Создать шаблон. Добавить задачи через бота.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#24](https://github.com/team-dev-spring-2022/teamBanana/issues/24), [#25](https://github.com/team-dev-spring-2022/teamBanana/issues/25) are still not solved.

**Comment by 0pdd** [comment]
@Arkaides the puzzle [#25](https://github.com/team-dev-spring-2022/teamBanana/issues/25) is still not solved; solved: [#24](https://github.com/team-dev-spring-2022/teamBanana/issues/24).

**Comment by 0pdd** [comment]
@Arkaides all 2 puzzles are solved here: [#24](https://github.com/team-dev-spring-2022/teamBanana/issues/24), [#25](https://github.com/team-dev-spring-2022/teamBanana/issues/25).
