### ISSUE TITLE
Добавить страницу входа

### ISSUE THREAD

**Issue by Arkaides** [team-dev-spring-2022/teamBanana#22]
Создать шаблон. Добавить задачи через бота.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#27](https://github.com/team-dev-spring-2022/teamBanana/issues/27), [#28](https://github.com/team-dev-spring-2022/teamBanana/issues/28) are still not solved.

**Comment by 0pdd** [comment]
@Arkaides the puzzle [#27](https://github.com/team-dev-spring-2022/teamBanana/issues/27) is still not solved; solved: [#28](https://github.com/team-dev-spring-2022/teamBanana/issues/28).

**Comment by 0pdd** [comment]
@Arkaides all 2 puzzles are solved here: [#27](https://github.com/team-dev-spring-2022/teamBanana/issues/27), [#28](https://github.com/team-dev-spring-2022/teamBanana/issues/28).
