### ISSUE TITLE
Добавить страницу регистрации

### ISSUE THREAD

**Issue by Arkaides** [team-dev-spring-2022/teamBanana#33]
Создать шаблон. Добавить задачи через бота.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#36](https://github.com/team-dev-spring-2022/teamBanana/issues/36), [#37](https://github.com/team-dev-spring-2022/teamBanana/issues/37) are still not solved.

**Comment by 0pdd** [comment]
@Arkaides the puzzle [#36](https://github.com/team-dev-spring-2022/teamBanana/issues/36) is still not solved; solved: [#37](https://github.com/team-dev-spring-2022/teamBanana/issues/37).

**Comment by 0pdd** [comment]
@Arkaides all 2 puzzles are solved here: [#36](https://github.com/team-dev-spring-2022/teamBanana/issues/36), [#37](https://github.com/team-dev-spring-2022/teamBanana/issues/37).
