### ISSUE TITLE
Добавить страницу с задачами

### ISSUE THREAD

**Issue by Arkaides** [team-dev-spring-2022/teamBanana#35]
Создать шаблон. Добавить задачи через бота.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#41](https://github.com/team-dev-spring-2022/teamBanana/issues/41), [#42](https://github.com/team-dev-spring-2022/teamBanana/issues/42) are still not solved.

**Comment by 0pdd** [comment]
@Arkaides the puzzle [#42](https://github.com/team-dev-spring-2022/teamBanana/issues/42) is still not solved; solved: [#41](https://github.com/team-dev-spring-2022/teamBanana/issues/41).

**Comment by 0pdd** [comment]
@Arkaides all 2 puzzles are solved here: [#41](https://github.com/team-dev-spring-2022/teamBanana/issues/41), [#42](https://github.com/team-dev-spring-2022/teamBanana/issues/42).
