### ISSUE TITLE
Добавить начальную страницу

### ISSUE THREAD

**Issue by Arkaides** [team-dev-spring-2022/teamBanana#4]
Создать шаблон. Добавить задачи через бота.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#16](https://github.com/team-dev-spring-2022/teamBanana/issues/16), [#17](https://github.com/team-dev-spring-2022/teamBanana/issues/17) are still not solved.

**Comment by 0pdd** [comment]
@Arkaides 2 puzzles [#29](https://github.com/team-dev-spring-2022/teamBanana/issues/29), [#30](https://github.com/team-dev-spring-2022/teamBanana/issues/30) are still not solved; solved: [#16](https://github.com/team-dev-spring-2022/teamBanana/issues/16), [#17](https://github.com/team-dev-spring-2022/teamBanana/issues/17).

**Comment by 0pdd** [comment]
@Arkaides the puzzle [#30](https://github.com/team-dev-spring-2022/teamBanana/issues/30) is still not solved; solved: [#16](https://github.com/team-dev-spring-2022/teamBanana/issues/16), [#17](https://github.com/team-dev-spring-2022/teamBanana/issues/17), [#29](https://github.com/team-dev-spring-2022/teamBanana/issues/29).

**Comment by 0pdd** [comment]
@Arkaides all 4 puzzles are solved here: [#16](https://github.com/team-dev-spring-2022/teamBanana/issues/16), [#17](https://github.com/team-dev-spring-2022/teamBanana/issues/17), [#29](https://github.com/team-dev-spring-2022/teamBanana/issues/29), [#30](https://github.com/team-dev-spring-2022/teamBanana/issues/30).
